import drumsUrl from "./drums.wav";
import peaksUrl from "./peaks.json?url";
import restUrl from "./rest.wav";

/**
 * Bundled fixture stems, generated by `scripts/make-fixtures.mjs`. They let the
 * player run end-to-end before the real separation pipeline (issue #4) exists;
 * `player-provider` falls back to these whenever a song's `app://` files are
 * absent.
 */
export const FIXTURE_ASSETS = {
  drumsUrl,
  peaksUrl,
  restUrl,
} as const;
